### ISSUE TITLE
Event history

### ISSUE THREAD

**Issue by cvhoang** [DanielNagy/astralpool_halo_chlorinator#6]
Thanks for your work. Just wondering if event history can be retrieved. I found it to be useful for knowing when to add salt or when the water flow is low.

**Comment by DanielNagy** [comment]
If it's retrievable in the mobile app, then it is possible. But would need to understand the data format, and also how to present it in home assistant. 

Would need to look further into the feasibility of this.

**Comment by cvhoang** [comment]
It's in the mobile app: Settings -> Stats -> View Events.

I think you need to register to receive the events which triggers the Halo to send the history one by one.

Cheers.

**Comment by DanielNagy** [comment]
As of App version 1.5.2, the events button is no longer there.

Given it has been removed. I will not look further into this.

**Comment by phrak** [comment]
App v1.5.3 still has the Events button

![Screenshot_20240525-084636](https://github.com/DanielNagy/astralpool_halo_chlorinator/assets/8485215/016bb848-03d6-4139-a78b-6d5e3376c6e3)

**Comment by DanielNagy** [comment]
Your stats are a little high 😂. Power cycle your chlorinator. 

I'm under the understanding it is being removed.

**Comment by phrak** [comment]
> Your stats are a little high 😂. Power cycle your chlorinator.
> 
> I'm under the understanding it is being removed.

Yeah I know, I just did the FW2.3 upgrade that morning.
Solved itself after the midnight reset :)
